version: 2
machine:
  environment:
    PROJECT_ID: katedeploy
    CLUSTER_NAME: eatout-kate
    COMPUTE_ZONE: us-central1-a
    
    DEPLOYMENT_NAME: assessment-kate
    CONTAINER_NAME: kate-app

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4

      - image: circleci/postgres:9.6
        environment:
          POSTGRES_DB: postgres2
          POSTGRES_USER: postgres2
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            nosetests tests

  deploy:
      docker:
        - image: google/cloud-sdk
          environment:
            GPROJECT_ID: katedeploy
            CLUSTER_NAME: eatout-kate
            COMPUTE_ZONE: us-central1-a

            DEPLOYMENT_NAME: assessment-kate
            CONTAINER_NAME: kate-app

      steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build and deploy application
            command: |
              chmod +x scripts/deploy.sh && bash scripts/deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master