kind: Service
apiVersion: v1
metadata:
  #Service name
  name: assessment-kate
spec:
  selector:
    app: katedeploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer